class MyException extends Exception { // membuat jenis error baru bernama MyException yang merupakan turunan dari Exception

    private String Teks;
    MyException(String s) {
        Teks = "Exception generated by: " + s; // membuat constructor untuk mencetak pesan Teks
        System.out.println(Teks);
    }
}

class Eksepsi {
    static void tampil(String s) throws Exception { // Method ini menerima parameter string
        System.out.println("Tampil"); // program akan mencetak "Tampil"
        if (s.equals("amir")) { // lalu akan di cek apakah s sama dengan "amir"
            throw new MyException(s); // jika ya, maka akan melempar MyException
        }
        System.out.println("OK!"); // jika bukan "amir" maka akan mencetak "OK!"
    }

    public static void main(String[] args) throws Exception {
        try {
            tampil("ali"); // program mencoba tampil("ali"), karna "ali" tidak sama dengan "amir" maka mencetak "Tampil" dan "OK!"
            tampil("amir"); // karna "amir" sama dengan "amir" maka akan melempar MyException, output nya "Exception generated by: amir"
        }
        catch (MyException ex) {
            System.out.println("Tangkap: " + ex); // karna bagian tampil("amir") maka masuk ke sini dan mencetak "Tangkap: MyException"
        }
    }
}
